name: C++ Project Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up CMake
        uses: ilammy/setup-cmake@v2
        
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
        
      - name: Build Project
        run: cmake --build ${{github.workspace}}/build --config Release

      # You can add more steps here for testing, deployment, etc.
